export const boardmembers = [
  {
    what: "Präsident",
    who: "Rohner Hermann",
    where: "Kirchgasse 23<br>8266 Steckborn",
    mobile: "079 641 99 65",
    landline: "",
    mail: "pittihr@gmail.com",
  },
  {
    what: "Vizepräsident",
    who: "Bollinger Roger",
    where: "Stimmerstrasse 94<br>8200 Schaffhausen",
    mobile: "079 630 78 38",
    landline: "052 625 90 78",
    mail: "roger.bollinger@greenmail.ch",
  },
  {
    what: "Materialverwalter",
    who: "Bollinger Roger",
    where: "Stimmerstrasse 94<br>8200 Schaffhausen",
    mobile: "079 630 78 38",
    landline: "052 625 90 78",
    mail: "roger.bollinger@greenmail.ch",
  },
  {
    what: "Wettkampforganisator",
    who: "Bollinger Roger",
    where: "Stimmerstrasse 94<br>8200 Schaffhausen",
    mobile: "079 630 78 38",
    landline: "052 625 90 78",
    mail: "roger.bollinger@greenmail.ch",
  },
  {
    what: "Aktuar",
    who: "Tanner Stefan",
    where: "Hauptstrasse 3<br>8232 Merishausen",
    mobile: "078 710 63 66",
    landline: "",
    mail: "stefan.tanner@swissonline.ch",
  },
  {
    what: "Kassier",
    who: "Geissler Patrick",
    where: "Untergassweg 24a<br>8215 Hallau",
    mobile: "079 352 41 62",
    landline: "",
    mail: "patrick.geissler@inpuncto-ag.ch",
  },
  {
    what: "Kantonalcup",
    who: "Schudel Erich",
    where: "Dorfstrasse 30<br>8228 Beggingen",
    mobile: "077 463 95 83",
    landline: "",
    mail: "tschudiii@gmx.ch",
  },
  {
    what: "10m LUPI",
    who: "Vakant",
    where: "ad interim Bollinger Roger",
    mobile: "",
    landline: "",
    mail: "",
  },
  {
    what: "25m ISSF",
    who: "Vakant",
    where: "ad interim Bollinger Roger",
    mobile: "",
    landline: "",
    mail: "",
  },
  {
    what: "50m Freipistole",
    who: "Vakant",
    where: "",
    mobile: "",
    landline: "",
    mail: "",
  },
  {
    what: "50m Armeepistole SPK",
    who: "Vakant",
    where: "",
    mobile: "",
    landline: "",
    mail: "",
  },
  {
    what: "300m Ordonnanzgewehr",
    who: "Rohner Hermann",
    where: "Störenbergstrasse 23 <br> 8265 Mammern",
    mobile: "079 641 99 65",
    landline: "",
    mail: "pittihr@gmail.com",
  },
  {
    what: "300m Sportgewehr",
    who: "Baumann Franz",
    where: "Sägistieg 10<br>8240 Thayngen",
    mobile: "079 532 63 61",
    landline: "",
    mail: "heifra.baumann@bluewin.ch",
  },
];
