export const boardmembers = [
  {
    what: "Präsident",
    who: "Rohner Hermann",
    where: "Kirchgasse 23<br>8266 Steckborn",
    mobile: "079 641 99 65",
    landline: "",
    mail: "pittihr@gmail.com",
  },
  {
    what: "Vizepräsident",
    who: "Bollinger Roger",
    where: "Stimmerstrasse 94<br>8200 Schaffhausen",
    mobile: "079 630 78 38",
    landline: "052 625 90 78",
    mail: "roger.bollinger@greenmail.ch",
  },
  {
    what: "Materialverwalter",
    who: "Bollinger Roger",
    where: "Stimmerstrasse 94<br>8200 Schaffhausen",
    mobile: "079 630 78 38",
    landline: "052 625 90 78",
    mail: "roger.bollinger@greenmail.ch",
  },
  {
    what: "Wettkampforganisator",
    who: "Bollinger Roger",
    where: "Stimmerstrasse 94<br>8200 Schaffhausen",
    mobile: "079 630 78 38",
    landline: "052 625 90 78",
    mail: "roger.bollinger@greenmail.ch",
  },
  {
    what: "Aktuar",
    who: "vakant",
    where: "",
    mobile: "",
    landline: "",
    mail: "",
  },
  {
    what: "Kassier",
    who: "vakant",
    where: "",
    mobile: "",
    landline: "",
    mail: "",
  },
  {
    what: "Kantonalcup",
    who: "Schudel Erich",
    where: "Dorfstrasse 30<br>8228 Beggingen",
    mobile: "077 463 95 83",
    landline: "",
    mail: "tschudiii@gmx.ch",
  },
  {
    what: "10m LUPI",
    who: "Vakant",
    where: "ad interim Bollinger Roger",
    mobile: "",
    landline: "",
    mail: "",
  },
  {
    what: "25m ISSF",
    who: "Vakant",
    where: "ad interim Bollinger Roger",
    mobile: "",
    landline: "",
    mail: "",
  },
  {
    what: "50m Freipistole",
    who: "Vakant",
    where: "",
    mobile: "",
    landline: "",
    mail: "",
  },
  {
    what: "50m Armeepistole SPK",
    who: "Vakant",
    where: "",
    mobile: "",
    landline: "",
    mail: "",
  },
  {
    what: "300m Ordonnanzgewehr",
    who: "Rohner Hermann",
    where: "Kirchgasse 23<br>8266 Steckborn",
    mobile: "079 641 99 65",
    landline: "",
    mail: "pittihr@gmail.com",
  },
  {
    what: "300m Sportgewehr",
    who: "vakant",
    where: "",
    mobile: "",
    landline: "",
    mail: "",
  },
];
